### ISSUE TITLE
Proposal: step conditions based on externally provided variable

### ISSUE THREAD

**Issue by jvantillo** [estafette/estafette-ci-builder#10]
**Background**
As discussed, in the future we wish to be able to run Estafette without GoCD. The latter currently provides a couple of features, specifically the ability to break a larger pipeline into multiple steps (compile, deploy to A, deploy to B, etc). Right now, Estafette doesn't yet support 'manual steps', 'quality gates' or related principles that allow us to do this. Right now, all the Estafette pipelines run sequentially.

We currently have one project where we'd like to experiment further with breaking the dependency on GoCD. As such, we want all pipelines to be Estafette-based. However, we do not wish to be dependent on GoCD bringing in external variables, or requiring multiple Estafette scripts.

**Proposal**
Technically, we can have a single script, which is triggered from multiple GoCD pipelines. Step conditions would allow us to have one script, and then conditionally run certain steps:
```
pipelines:
  step-a:
    image: <IMG>
    commands:
    - <CMD>

  step-b-one:
    image: <IMG>
    commands:
    - <CMD>
    when:
       stage == "deploy_staging"

  step-b-two:
    image: <IMG>
    commands:
    - <CMD>
    when:
       stage == "deploy_prod"
```
Running this from different pipelines would be mean that `step-a` is always executed, but the other steps only if their condition evaluates to `true`.

**Implementation**
This can almost be achieved, the only missing link is the ability to specify a condition like this. The idea here is to implement the ability to define a well-known condition name (`stage`) and have Estafette pick up its value from a well-known env var (like `ESTAFETTE_STAGE`). This variable would be configured in GoCD, on pipelines that just run the estafette builder in combination with this var.

**Forward compatibility**
Eventually this functionality might become obsolete when Estafette implements the topics mentioned at the top of this issue.
