### ISSUE TITLE
Proposal: global variables

### ISSUE THREAD

**Issue by jvantillo** [estafette/estafette-ci-builder#9]
As previously discussed, we're considering to add global variables to the CI builder. I'd like to further agree on the functionality and changes to the yaml format.

Example:
```
labels:
  app: <APP NAME>
  language: dotnet-core

env:
  VAR_A: "Greetings"
  VAR_B: "World"

pipelines:
  do-some-work:
    image: <SOME IMAGE>
    env:
       VAR_A: "Hello"
    commands:
    - echo ${VAR_A} ${VAR_B}

  do-more-work:
    image: <SOME IMAGE>
    commands:
    - echo ${VAR_A} ${VAR_B}
```

Expected output:
```
[do-some-work] Hello World
[do-more-work] Greetings World
```

Two features are shown:

* Before the definition of the pipelines, you MAY define one or more global variables. Each of the global variables MUST be propagated to every pipeline. Each pipeline will receive a copy of the global variable, any modifications by a pipeline will not alter the global variables.
* In a pipeline you MAY override one or more global variables by explicitly defining them again.
